---
version: '2.1'

services:

#  em-viewer-web:
#    ports:
#     - 8084:8080

#  em-annotation-app:
#    ports:
#      - 4621:4621
#      - 5005:5005

  em-annotation-database:
    ports:
      - 5432:5432

  idam-registration-web:
    ports:
    - 9001:8000

  idam-authentication-web:
    ports:
    - 9000:8000

  idam-api:
    ports:
      - 8081:8080

  idam-database:
    ports:
      - 5430:5432

  service-auth-provider-api:
    ports:
      - 8082:8080
