version: '2.1'

services:
#  em-annotation-app:
#    build:
#      context: .
#      args:
#        - http_proxy
#        - https_proxy
#        - no_proxy
#    image: docker.artifactory.reform.hmcts.net/evidence/em-annotation-app:latest
#    environment:
#      - NODE_ENV=development
#      - SERVER_PORT=8080
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://em-annotation-app-database:5432/evidence
#      - IDAM_CLIENT_URL=http://idam-api:8080
#      - PROVIDER_SERVICE_CLIENT_URL=http://service-auth-provider-api:8080
#      - http_proxy=
#      - https_proxy=
#      - no_proxy=
#      # these environment variables are used by java-logging library
#      - ROOT_APPENDER
#      - JSON_CONSOLE_PRETTY_PRINT
#      - ROOT_LOGGING_LEVEL
#      - REFORM_SERVICE_NAME
#      - REFORM_TEAM
#      - REFORM_ENVIRONMENT
#    links:
#      - em-annotation-app-database
#    depends_on:
#      - em-annotation-app-database
#    ports:
#      # check .env
#      - $SERVER_PORT:8080

  em-annotation-app-database:
    build:
      context: ./docker/database
    image: docker.artifactory.reform.hmcts.net/evidence/em-annotation-app-database:latest
    ports:
      # check .env
      - 5432:5432
