version: '2.1'

services:
  em-annotation-app:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/evidence/em-annotation-app:latest
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    ports:
      # check .env
      - $SERVER_PORT:$SERVER_PORT

  em-annotation-database:
    build:
      context: ./docker/database
    image: docker.artifactory.reform.hmcts.net/evidence/em-annotation-app-database:latest
