api:
  version: 0.0.1

spring:
  data:
    rest:
      detection-strategy: annotated
  jackson:
    serialization:
      indent_output: true
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: postgresql
    show-sql: ${SHOW_SQL:true}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/annotation}
    username: ${SPRING_DATASOURCE_USERNAME:annotation}
    password: ${SPRING_DATASOURCE_PASSWORD:annotation}
    platform: postgresql
    time-between-eviction-runs-millis: ${STALE_CONN_EVICTION_FREQUENCY:60000}
    tomcat:
      max-active: ${MAX_ACTIVE_DB_CONNECTIONS:50} # Maximum number of active connections that can be allocated from this pool at the same time.
      max-idle: ${MAX_IDLE_DB_CONNECTIONS:25}
      max-wait: ${MAX_WAIT_DB_CONNECTIONS:10000} # Number of ms to wait before throwing an exception if no connection is available.
      test-on-borrow: ${TEST_ON_BORROW_DB_CONNECTION:true} # Validate the connection before borrowing it from the pool.

liquibase:
 enabled: ${ENABLE_DB_MIGRATE:true}
 change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: ${SERVER_PORT:4621}

authorization:
  case-worker-roles: ${CASE_WORKER_ROLES:caseworker-probate,caseworker-cmc,caseworker-sscs,caseworker-divorce}
  s2s-names-whitelist: ${S2S_NAMES_WHITELIST:sscs,divorce,ccd,em_gw}

auth:
  idam:
    client:
      baseUrl: ${IDAM_USER_BASE_URI:http://localhost:4501}
  provider:
    service:
      client:
        baseUrl: ${IDAM_S2S_BASE_URI:http://localhost:4502}

security:
  headers:
    cache: false

logging:
  level:
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    uk.gov.hmcts.reform.em.annotation: ${LOG_LEVEL_DM:INFO}

errors:
  globalIncludeStackTrace: ${SHOW_STACK_TRACE:true}

info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:evidence}
    name: ${PACKAGES_NAME:em-anno-app}
#    version: ${PACKAGES_VERSION:unknown}

health:
  status:
    order:
    - FATAL
    - DOWN
    - UNKNOWN
    - UP
  disk:
    threshold: ${HEALTH_DISK_THRESHOLD:262144000}

endpoints:
  health:
    sensitive: ${ENDPOINTS_HEALTH_SENSITIVE:false}
  info:
    sensitive: ${ENDPOINTS_INFO_SENSITIVE:false}

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:false}
  diskspace:
    enabled: true
  db:
    enabled: true

toggle:
  includeidamhealth: ${ENABLE_IDAM_HEALTH_CHECK:false}
