version: '2.1'

services:
#  em-anno:
#    build:
#      context: ../.
#    image: hmcts/em-anno:latest
#    environment:
#      - SERVER_PORT=8080
#      - IDAM_USER_BASE_URI=http://idam-api:8080
#      - IDAM_S2S_BASE_URI=http://service-auth-provider-app:8489
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://em-anno-db:5432/annotation
##      logging env vars
#      - ROOT_APPENDER=JSON_CONSOLE
#      - JSON_CONSOLE_PRETTY_PRINT=false
#      - REFORM_SERVICE_TYPE=java
#      - REFORM_SERVICE_NAME=em-anno
#      - REFORM_TEAM=evidence
#      - REFORM_ENVIRONMENT=docker
#    links:
#     - em-anno-db
#     - document-management-store
#     - idam-api
#     - service-auth-provider-app
#    depends_on:
#     - em-anno-db
#     - document-management-store
#     - idam-api
#     - service-auth-provider-app

  em-anno-db:
    build:
      context: ../database
    image: hmcts/em-anno-db:latest

  em-redact:
    image: hmcts/em-redact:latest
    environment:
      - SERVER_PORT=8080
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-app:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://em-redaction-app-database:5432/redaction
      # these environment variables are used by java-logging library
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=true
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=em-redaction-app
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
    links:
     - em-redaction-app-database
     - idam-api
     - service-auth-provider-app
    depends_on:
     - em-redaction-app-database
     - idam-api
     - service-auth-provider-app

  em-redact-db:
    image: hmcts/em-redact-db:latest
