version: '2.1'

services:

  em-viewer-web:
    image: docker.artifactory.reform.hmcts.net/evidence/em-viewer-web:latest
    environment:
    - NODE_ENV=development
    - PORT=8080

  em-annotation-app:
    build:
      context: ../../.
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/evidence/em-annotation-app:latest
    environment:
      - NODE_ENV=development
      - SERVER_PORT=8080
      - IDAM_CLIENT_URL=http://idam-api:8080
      - PROVIDER_SERVICE_CLIENT_URL=http://service-auth-provider-api:8080
      - http_proxy=
      - https_proxy=
      - no_proxy=
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    links:
     - em-annotation-database
     - document-management-store
     - idam-api
     - service-auth-provider-api
    depends_on:
     - em-annotation-database
     - document-management-store
     - idam-api
     - service-auth-provider-api

  em-annotation-database:
    build:
      context: ../database
    image: docker.artifactory.reform.hmcts.net/evidence/em-annotation-app-database:latest
